# UCDD on spam evaluation

## Accept and preprocess the spam dataset

In [2]:
import numpy as np
import pandas as pd

In [10]:
from sklearn.preprocessing import MinMaxScaler


df = pd.read_csv("../Datasets_concept_drift/real_world_data/spam_dataset.csv")

print('df columns')
print(df.columns)

X = df.drop(columns=['Unnamed: 0', 'ACTUAL_LABEL'])
y = df["ACTUAL_LABEL"]

X_ref = X[:1468]
X_test = X[1468:]
y_ref = y[:1468]
y_test = y[1468:]

print('first rows of aba')
print(X_ref[['aba']])

X_ref = X_ref.to_numpy()
X_test = X_test.to_numpy()
y_ref = y_ref.to_numpy().reshape((len(y_ref.index), 1))
y_test = y_test.to_numpy().reshape((len(y_test.index), 1))

scaler = MinMaxScaler()
scaler.fit(X_ref)
X_ref = scaler.transform(X_ref)
X_test = scaler.transform(X_test)

print('\nreference data')
print(X_ref.shape)
print(X_ref)
print('\nreference labels')
print(y_ref.shape)
print('\ntesting data')
print(X_test.shape)
print(X_test)
print('\ntesting labels')
print(y_test.shape)

df columns
Index(['Unnamed: 0', 'aa', 'aba', 'abandon', 'abb', 'abbey', 'abbrevi',
       'abdomin', 'abduct', 'aberr',
       ...
       'zig', 'zimbabw', 'zinc', 'zip', 'zodiac', 'zone', 'zoo', 'zoom',
       'zowi', 'ACTUAL_LABEL'],
      dtype='object', length=10729)
first rows of aba
      aba
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
...   ...
1463  0.0
1464  0.0
1465  0.0
1466  0.0
1467  0.0

[1468 rows x 1 columns]
scaler min_
[0. 0. 0. ... 0. 0. 0.]
scaler scale_
[6.31423128 1.         6.53268125 ... 1.         6.22316195 1.        ]
scaler data_min_
[0. 0. 0. ... 0. 0. 0.]
scaler data_max_
[0.15837241 0.         0.1530765  ... 0.         0.16069002 0.        ]
scaler data_range_
[0.15837241 0.         0.1530765  ... 0.         0.16069002 0.        ]
0.0006779101229450423
transformed reference data with 

reference data
(1468, 10727)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0.

## Split the dataset to batches

### Size=100

In [24]:
from eval_helpers import helpers

X_test_batches_100, y_test_batches_100 = helpers.split_to_fixed_size_batches(X_test, y_test, batch_size=100)
X_ref_batches_100, y_ref_batches_100 = helpers.split_to_fixed_size_batches(X_ref, y_ref, batch_size=100)

print('# test batches 100:')
print(len(X_test_batches_100))
print(len(y_test_batches_100))
print('# ref batches 100:')
print(len(X_ref_batches_100))
print(len(y_ref_batches_100))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(100, 10727)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(100, 10727)
# test batches 100:
29
29
# ref batches 100:
14
14


### Size=50

In [25]:
from eval_helpers import helpers

X_test_batches_50, y_test_batches_50 = helpers.split_to_fixed_size_batches(X_test, y_test, batch_size=50)
X_ref_batches_50, y_ref_batches_50 = helpers.split_to_fixed_size_batches(X_ref, y_ref, batch_size=50)

print('# test batches 50:')
print(len(X_test_batches_50))
print(len(y_test_batches_50))
print('# ref batches 50:')
print(len(X_ref_batches_50))
print(len(y_ref_batches_50))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(50, 10727)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(50, 10727)
# test batches 50:
58
58
# ref batches 50:
29
29


### Size=20

In [26]:
from eval_helpers import helpers

X_test_batches_20, y_test_batches_20 = helpers.split_to_fixed_size_batches(X_test, y_test, batch_size=20)
X_ref_batches_20, y_ref_batches_20 = helpers.split_to_fixed_size_batches(X_ref, y_ref, batch_size=20)

print('# test batches 20:')
print(len(X_test_batches_20))
print(len(y_test_batches_20))
print('# ref batches 20:')
print(len(X_ref_batches_20))
print(len(y_ref_batches_20))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(20, 10727)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(20, 10727)
# test batches 20:
146
146
# ref batches 20:
73
73


## Imports

In [27]:
import importlib
from eval_helpers import ucdd_eval_real_world
from eval_helpers import kmeans_verbose_helpers
from core import ucdd_supported_parameters as spms
from core import ucdd
importlib.reload(ucdd_eval_real_world)
importlib.reload(ucdd)
importlib.reload(kmeans_verbose_helpers)

something


<module 'eval_helpers.kmeans_verbose_helpers' from 'C:\\Users\\jpohl\\PycharmProjects\\clustering-drift-detection\\ucdd_improved\\eval_helpers\\kmeans_verbose_helpers.py'>

## Evaluation with size 100 batches


### Find suitable KMeans clustering parameters

In [12]:
kmeans_verbose_helpers.write_kmeans_results_ucdd_helper('spam_kmeans_100/spam_kmeans_100_output', X_ref_batches_100,
                                                        n_init=100, max_iter=500, tol=0,
                                                        random_state=1053)

filename spam_kmeans_100/spam_kmeans_100_output0.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output1.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output2.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output3.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output4.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output5.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output6.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output7.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output8.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output9.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output10.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output11.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output12.txt
random state: 1053
filename spam_kmeans_100/spam_kmeans_100_output13.txt
random 

### Use UCDD directly to obtain inspectable results

In [28]:
from core import ucdd
import importlib
importlib.reload(ucdd)

all_2d_drifts_100 = []
all_2d_cluster_classif_accs_100 = []

for random_state in [0, 100]:
    drifts_2d_arr_100, cluster_classif_accs_2d_arr_100 = ucdd.all_drifting_batches_parallel_all_info(
        X_ref_batches_100,
        X_test_batches_100,
        additional_check=True,
        n_init=100,
        max_iter=15000,
        tol=0,
        random_state=random_state,
        reference_label_batches=y_ref_batches_100,
        testing_label_batches=y_test_batches_100
    )
    all_2d_drifts_100.append(drifts_2d_arr_100)
    all_2d_cluster_classif_accs_100.append(cluster_classif_accs_2d_arr_100)

result_dict_100 = {
    'all_2d_drifts_100': all_2d_drifts_100,
    'all_2d_cluster_classif_accs_100': all_2d_cluster_classif_accs_100
}
np.save('spam_stats_100.npy', result_dict_100)

random_state
0
pool opened
random_state
100
pool opened


In [14]:
result_dict_100 = np.load('spam_stats_100.npy', allow_pickle=True).item()
print('resulting dictionary')
print(result_dict_100)
all_2d_drifts_100 = result_dict_100['all_2d_drifts_100']
# print('total number of drift detections:', len(X_ref_batches_100) * len(X_test_batches_100))
print('number of drift detection differences in the two runs:')
num_diffs = np.sum(all_2d_drifts_100[0] != all_2d_drifts_100[1])
print(num_diffs)

# print('expected total number of drift detections:', len(X_ref_batches_100) * len(X_test_batches_100))
print('actual total number of drift detections:', all_2d_drifts_100[0].size)
print('total number of drift signals:', np.sum(all_2d_drifts_100[0]))


resulting dictionary
{'all_2d_drifts_100': [array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ Tru

## Evaluation with size 50 batches

### Find suitable KMeans clustering parameters

In [18]:
kmeans_verbose_helpers.write_kmeans_results_ucdd_helper('spam_kmeans_50/spam_kmeans_50_output', X_ref_batches_50,
                                                        n_init=50, max_iter=500, tol=0,
                                                        random_state=1053)

filename spam_kmeans_50/spam_kmeans_50_output0.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output1.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output2.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output3.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output4.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output5.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output6.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output7.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output8.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output9.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output10.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output11.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output12.txt
random state: 1053
filename spam_kmeans_50/spam_kmeans_50_output13.txt
random state: 1053
filename spam_km

### Use UCDD directly to obtain inspectable results

In [30]:
from core import ucdd
import importlib
importlib.reload(ucdd)

all_2d_drifts_50 = []
all_2d_cluster_classif_accs_50 = []

for random_state in [0]:
    drifts_2d_arr_50, cluster_classif_accs_2d_arr_50 = ucdd.all_drifting_batches_parallel_all_info(
        X_ref_batches_50,
        X_test_batches_50,
        additional_check=True,
        n_init=100,
        max_iter=7000,
        tol=0,
        random_state=random_state,
        reference_label_batches=y_ref_batches_50,
        testing_label_batches=y_test_batches_50
    )
    all_2d_drifts_50.append(drifts_2d_arr_50)
    all_2d_cluster_classif_accs_50.append(cluster_classif_accs_2d_arr_50)

result_dict_50 = {
    'all_2d_drifts_50': all_2d_drifts_50,
    'all_2d_cluster_classif_accs_50': all_2d_cluster_classif_accs_50
}
np.save('spam_stats_50.npy', result_dict_50)

random_state
0
pool opened


In [16]:
result_dict_50 = np.load('spam_stats_50.npy', allow_pickle=True).item()
print('resulting dictionary')
print(result_dict_50)
all_2d_drifts_50 = result_dict_50['all_2d_drifts_50']
# print('total number of drift detections:', len(X_ref_batches_50) * len(X_test_batches_50))
print('actual total number of drift detections:', all_2d_drifts_50[0].size)
print('total number of drift signals:', np.sum(all_2d_drifts_50[0]))

resulting dictionary
{'all_2d_drifts_50': [array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])], 'all_2d_cluster_classif_accs_50': [array([[0.76, 0.75, 0.75, ..., 0.51, 0.51, 0.51],
       [0.76, 0.75, 0.75, ..., 0.51, 0.51, 0.51],
       [0.76, 0.75, 0.75, ..., 0.51, 0.51, 0.51],
       ...,
       [0.56, 0.57, 0.57, ..., 0.81, 0.81, 0.81],
       [0.55, 0.56, 0.56, ..., 0.8 , 0.8 , 0.8 ],
       [0.53, 0.52, 0.52, ..., 0.76, 0.76, 0.76]])]}
actual total number of drift detections: 1682
total number of drift signals: 1682


## Evaluation with size 20 batches

### Find suitable KMeans clustering parameters

In [19]:
kmeans_verbose_helpers.write_kmeans_results_ucdd_helper('spam_kmeans_20/spam_kmeans_20_output', X_ref_batches_20,
                                                        n_init=50, max_iter=500, tol=0,
                                                        random_state=1053)


filename spam_kmeans_20/spam_kmeans_20_output0.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output1.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output2.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output3.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output4.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output5.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output6.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output7.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output8.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output9.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output10.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output11.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output12.txt
random state: 1053
filename spam_kmeans_20/spam_kmeans_20_output13.txt
random state: 1053
filename spam_km

### Use UCDD directly to obtain inspectable results

In [33]:
from core import ucdd
import importlib
importlib.reload(ucdd)

all_2d_drifts_20 = []
all_2d_cluster_classif_accs_20 = []

for random_state in [0]:
    drifts_2d_arr_20, cluster_classif_accs_2d_arr_20 = ucdd.all_drifting_batches_parallel_all_info(
        X_ref_batches_20,
        X_test_batches_20,
        additional_check=True,
        n_init=40,
        max_iter=5000,
        tol=0,
        random_state=random_state,
        reference_label_batches=y_ref_batches_20,
        testing_label_batches=y_test_batches_20
    )
    all_2d_drifts_20.append(drifts_2d_arr_20)
    all_2d_cluster_classif_accs_20.append(cluster_classif_accs_2d_arr_20)

result_dict_20 = {
    'all_2d_drifts_20': all_2d_drifts_20,
    'all_2d_cluster_classif_accs_20': all_2d_cluster_classif_accs_20
}
np.save('spam_stats_20.npy', result_dict_20)

random_state
0
pool opened


In [18]:
result_dict_20 = np.load('spam_stats_20.npy', allow_pickle=True).item()
print('resulting dictionary')
print(result_dict_20)
all_2d_drifts_20 = result_dict_20['all_2d_drifts_20']
# print('total number of drift detections:', len(X_ref_batches_20) * len(X_test_batches_20))
print('actual total number of drift detections:', all_2d_drifts_20[0].size)
print('total number of drift signals:', np.sum(all_2d_drifts_20[0]))

resulting dictionary
{'all_2d_drifts_20': [array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])], 'all_2d_cluster_classif_accs_20': [array([[0.825, 0.725, 0.7  , ..., 0.525, 0.525, 0.8  ],
       [0.825, 0.725, 0.7  , ..., 0.525, 0.525, 0.8  ],
       [0.825, 0.725, 0.7  , ..., 0.525, 0.525, 0.8  ],
       ...,
       [0.6  , 0.5  , 0.525, ..., 0.7  , 0.7  , 0.575],
       [0.525, 0.625, 0.6  , ..., 0.775, 0.775, 0.5  ],
       [0.55 , 0.55 , 0.575, ..., 0.75 , 0.75 , 0.525]])]}
actual total number of drift detections: 10658
total number of drift signals: 10657
